# Generated by Django 4.2.6 on 2023-11-02 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stagiaires', '0002_alter_customuser_is_superuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etudiant',
            name='filiere',
        ),
    ]
