# Generated by Django 4.2.6 on 2023-11-02 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stagiaires', '0003_remove_etudiant_filiere'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='statut',
            field=models.CharField(choices=[('En attente', 'En attente'), ('Accepté', 'Accepté'), ('Refusé', 'Refusé'), ('Terminé', 'Terminé')], default='En attente', max_length=255),
        ),
    ]
