# Generated by Django 4.2.6 on 2023-11-10 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stagiaires', '0004_alter_stage_statut'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rapport',
            fields=[
                ('numeroRapport', models.AutoField(primary_key=True, serialize=False)),
                ('rapportStage', models.FileField(upload_to='documents/')),
                ('appreciation', models.FileField(null=True, upload_to='documents/')),
                ('statutRapport', models.CharField(choices=[('En attente', 'En attente'), ('Validé', 'Validé'), ('Refusé', 'Refusé')], default='En attente', max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='etudiant',
            name='rapport',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='etudiantRapport', to='stagiaires.stage'),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='etudiantStage', to='stagiaires.stage'),
        ),
    ]
