# Generated by Django 4.2.6 on 2023-11-10 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stagiaires', '0005_rapport_etudiant_rapport_alter_etudiant_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='rapport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='etudiantRapport', to='stagiaires.stage'),
        ),
    ]
