# Generated by Django 4.2.6 on 2023-11-11 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stagiaires', '0007_alter_etudiant_rapport'),
    ]

    operations = [
        migrations.AddField(
            model_name='rapport',
            name='sigleEval',
            field=models.FileField(null=True, upload_to='documents/'),
        ),
    ]
