# Generated by Django 4.2.6 on 2023-11-11 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stagiaires', '0008_rapport_sigleeval'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rapport',
            old_name='sigleEval',
            new_name='grilleEval',
        ),
    ]
