# Generated by Django 4.2.6 on 2023-11-11 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stagiaires', '0009_rename_sigleeval_rapport_grilleeval'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rapport',
            name='grilleEval',
        ),
    ]
