# Generated by Django 4.2.6 on 2023-11-12 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stagiaires', '0010_remove_rapport_grilleeval'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personnels',
            fields=[
                ('idPersonnel', models.AutoField(primary_key=True, serialize=False)),
                ('nomPersonnel', models.CharField(max_length=255)),
                ('prenomPersonnel', models.CharField(max_length=255)),
                ('im', models.CharField(max_length=255)),
                ('telephonePersonnel', models.CharField(max_length=255)),
                ('emailPersonnel', models.EmailField(max_length=254)),
            ],
        ),
        migrations.DeleteModel(
            name='Personnel',
        ),
    ]
