# Generated by Django 4.2.6 on 2023-11-12 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stagiaires', '0011_personnels_delete_personnel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Personnels',
            new_name='Personnel',
        ),
    ]
