# Generated by Django 4.2.6 on 2023-11-12 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stagiaires', '0012_rename_personnels_personnel'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='personnel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='etudiantPersonnel', to='stagiaires.personnel'),
        ),
    ]
