# Generated by Django 4.2.6 on 2023-11-12 19:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stagiaires', '0013_etudiant_personnel'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='demandeCompte', to=settings.AUTH_USER_MODEL),
        ),
    ]
