# Generated by Django 4.2.6 on 2023-12-05 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stagiaires', '0022_alter_customuser_is_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='rapport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etudiantRapport', to='stagiaires.rapport'),
        ),
    ]
