# Generated by Django 4.2.5 on 2023-12-07 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stagiaires', '0024_alter_etudiant_personnel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etudiant',
            name='ecole',
        ),
        migrations.AddField(
            model_name='stage',
            name='ecole',
            field=models.TextField(blank=True, null=True),
        ),
    ]
