# Generated by Django 4.2.5 on 2023-12-07 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stagiaires', '0025_remove_etudiant_ecole_stage_ecole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='rapport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='etudiantRapport', to='stagiaires.rapport'),
        ),
    ]
