from django.urls import path
from . import views
from django.contrib.auth.views import LoginView

urlpatterns = [
    path('', LoginView.as_view(template_name='login.html'), name='login'),
    path('navbar/', views.navbar, name='navbar'),
    path('custom_login/',views.custom_login, name='custom_login'),
    path('logout/', views.custom_logout, name='logout'),
    path('create_user/',views.create_user,name='create_user'),
    path('add/', views.add, name='add'),
    path('addrecord/', views.addrecord, name='addrecord'),
    path('addrecord2/', views.addrecord2, name='addrecord2'),
    path('navbar/delete/<str:numeroDemande>', views.delete, name='delete'),
    path('navbar/accept/<str:numeroDemande>', views.accept, name='accept'),
    path('navbar/refuse/<str:numeroDemande>', views.refuse, name='refuse'),
    path('navbar/termine/<str:numeroDemande>', views.termine, name='termine'),
    path('navbar/download_file/<int:numeroDemande>/<str:field_name>/', views.download_file, name='download_file'),
    path('navbar/download_rapport/<int:idEtudiant>/<str:field_name>/', views.download_rapport, name='download_rapport'),
    path('update/<str:matricule>', views.update, name='update'),
    path('update/updaterecord/<str:matricule>', views.updaterecord, name='updaterecord'),
    path('statistique/', views.statistique, name='statistique'),
    path('faire_demande/', views.faire_demande, name='faire_demande'),
    path('monome/', views.monome, name='monome'),
    path('binome/', views.binome, name='binome'),
    path('demande/', views.demande, name='demande'),
    path('demande_filtreDSI/', views.demande_filtreDSI, name='demande_filtreDSI'),
    path('demande_filtreDRH/', views.demande_filtreDRH, name='demande_filtreDRH'),
    path('demande_filtreDAF/', views.demande_filtreDAF, name='demande_filtreDAF'),
    path('demande_search/', views.demande_search, name='demande_search'),
    path('demande_acceptee/', views.demande_acceptee, name='demande_acceptee'),
    path('demande_refusee/', views.demande_refusee, name='demande_refusee'),
    path('demande_modifiee/<int:idEtudiant>', views.demande_modifiee, name='demande_modifiee'),
    path('modifier_demande/<int:idEtudiant>', views.modifier_demande, name='modifier_demande'),
    path('stage_termine/', views.stage_termine, name='stage_termine'),
    path('stage_expire/', views.stage_expire, name='stage_expire'),
    path('rapport/', views.rapport, name='rapport'),
    path('rapport_search/', views.rapport_search, name='rapport_search'),
    path('rapportAttente/', views.rapportAttente, name='rapportAttente'),
    path('rapportValide/', views.rapportValide, name='rapportValide'),
    path('rapportRefuse/', views.rapportRefuse, name='rapportRefuse'),
    path('rapport_valide/<int:idEtudiant>/', views.rapport_valide, name='rapport_valide'),
    path('rapport_refuse/<int:idEtudiant>/', views.rapport_refuse, name='rapport_refuse'),
    path('faire_rapport/', views.faire_rapport, name='faire_rapport'),
    path('ajouter_rapport/<int:idEtudiant>/', views.ajouter_rapport, name='ajouter_rapport'),
    path('ajouter_appreciation/<int:idEtudiant>/', views.ajouter_appreciation, name='ajouter_appreciation'),
    path('delete_rapport/<int:idEtudiant>/', views.delete_rapport, name='delete_rapport'),
    path('delete_user/<int:id>/', views.delete_user, name='delete_user'),
    path('user/', views.user, name='user'),
    path('user_admin/', views.user_admin, name='user_admin'),
    path('user_membre/', views.user_membre, name='user_membre'),
    path('user_search/', views.user_search, name='user_search'),
    path('personnel/', views.personnel, name='personnel'),
    path('personnel_search/', views.personnel_search, name='personnel_search'),
    path('ajouter_personnel/', views.ajouter_personnel, name='ajouter_personnel'),
    path('ajouter_personnel/<int:idPersonnel>/', views.delete_personnel, name='delete_personnel'),
    path('formulaire_personnel/', views.formulaire_personnel, name='formulaire_personnel'),
    path('affecter_personnel/<int:idPersonnel>/', views.affecter_personnel, name='affecter_personnel'),
    path('grilleEval/<int:idEtudiant>/', views.grilleEval, name='grilleEval'),
    path('grilleEval2/<int:idEtudiant>/', views.grilleEval2, name='grilleEval2'),
    path('fichetech/<int:idStage>/', views.fichetech, name='fichetech'),
    path('attestation/<int:idEtudiant>/', views.attestation, name='attestation'),
    path('autre/', views.autre, name='autre'),
]